### ISSUE TITLE
Vertical metrics regression

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/BitterPro#10]
I don't think the vertical metrics got update in #9.

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/82207337-93170d80-9901-11ea-96b8-664453c3aa86.gif)

In #5, I recommended the following:

sTypoAscender: 935
sTypoDescender: -265
sTypoLineGap: 0
hhea Ascent: 935
hhea Descent: -265
hhea Linegap: 0
Win Ascent: 983
Win Descent: 243

**Comment by pichotta** [comment]
@moyogo 
see above

Also, before the next build I am looking into this https://github.com/TypeNetwork/Bitter/commits/master

**Comment by moyogo** [comment]
I’ve pushed a branch that sets the line height metrics to match GF.

**Comment by moyogo** [comment]
@m4rc1e Initially I hadn’t changed the line height metrics because they made sense with the glyph set that has a lot of taller glyphs.
