### ISSUE TITLE
PR in solmatas/BitterPro

### ISSUE THREAD

**Issue by solmatas** [TypeNetwork/BitterPro#13]
Could you please submit a PR in my repo, so can I merge your files in the original repository?
Thanks for your great work!

**Comment by solmatas** [comment]
Hi!
I am writing again because I have to work on this project doing an extension and I prefer to avoid doing a detached branch, that would make merging more difficult. Can you please submit a pull request so I can merge your files in the original repository? Thanks!

**Comment by pichotta** [comment]
@solmatas 
The weight axis variable font for **BitterPro** is complete. Thank you for accepting the pull request to merge the [wght].ttf and the .ufo sources into the master.

**Comment by pichotta** [comment]
@solmatas 
See the recent build with the most current gftools
https://github.com/TypeNetwork/Bitter/pull/16

**Comment by solmatas** [comment]
Thank you very much, Jill.
